RobotName: "walkman"

GazeboXBotPlugin:
  gains:
    RShSag:   {p: 4000, d: 10}
    RShLat:   {p: 3000, d: 10}
    RShYaw:   {p: 3000, d: 10}
    RElbj:    {p: 3000, d: 10}
    RWrj1:    {p: 1500, d: 10}
    LShSag:   {p: 4000, d: 10}
    LShLat:   {p: 3000, d: 10}
    LShYaw:   {p: 3000, d: 10}
    LElbj:    {p: 3000, d: 10}
    LWrj1:    {p: 1500, d: 10}
    WaistYaw: {p: 8000, d: 30}
    WaistLat: {p: 8000, d: 30}
    LHipYaw:  {p: 3000, d: 10}
    RHipYaw:  {p: 3000, d: 10}
    RHipLat:  {p: 8000, d: 30}
    RHipSag:  {p: 8000, d: 30}
    RKneeSag: {p: 8000, d: 30}
    RAnkSag:  {p: 8000, d: 30}
    RAnkLat:  {p: 8000, d: 30}
    LHipLat:  {p: 8000, d: 30}
    LHipSag:  {p: 8000, d: 30}
    LKneeSag: {p: 8000, d: 30}
    LAnkSag:  {p: 8000, d: 30}
    LAnkLat:  {p: 8000, d: 30}

    
HALInterface:
  lib_file: "libXBotEcat"
  lib_name: "ETHERCAT"
  
x_bot_ecat:
  name: XBotCore
  sdo_xddp_prefix : 
  # periodic - priority if needed here

ec_board_ctrl:
  eth_iface: rteth0
  sync_cycle_time_ns: 1000000
  sync_cycle_offset_ns: 0
  power_off_boards: false
  use_pipes: false
  
    

#############################
# HEAD & HANDS
#############################

#
LpESC_1:
  control_mode: idle
  sign: -1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

#
LpESC_2:
  control_mode: idle
  sign: -1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

# RA_HA = 19
LpESC_19:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

# LA_HA = 29
LpESC_29:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

#############################
# RIGHT LEG
#############################

# RL_H_R = 41
HpESC_41:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [100.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [200.0, 20.0, 5.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 4.0, 0.01, 0.8]

# RL_H_Y = 42
HpESC_42:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [180.0 , 0.0 , 3.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 10.0, 5.0, 0.01, 0.8]

# RL_H_P = 43
HpESC_43:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [700.0 , 0.0 , 10.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [300.0, 60.0, 5.0, 0.01, 0.8]

# RL_K = 44
HpESC_44:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [500.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 10.0, 5.0, 0.01, 0.8]

# RL_A_P = 45
HpESC_45:
  control_mode: idle
  sign: -1
  pos_offset: -20
  pid :
    position: [500.0 , 0.0 , 2.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 10.0, 5.0, 0.01, 0.8]

# RL_A_R = 46
HpESC_46:
  control_mode: idle
  sign: -1
  pos_offset: 0
  pid :
    position: [80.0 , 0.0 , 4.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 10.0, 5.0, 0.01, 0.8]

#############################
# LEFT LEG
#############################

# LL_H_Y = 51
HpESC_51:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [800.0 , 0.0 , 12.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [300.0, 60.0, 5.0, 0.01, 0.8]

# LL_H_R = 52
HpESC_52:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [180.0 , 0.0 , 3.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 10.0, 5.0, 0.01, 0.8]

# LL_H_P = 53
HpESC_53:
  control_mode: idle
  sign: -1
  pos_offset: 0
  pid :
    position: [700.0 , 0.0 , 10.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [300.0, 60.0, 5.0, 0.01, 0.8]

# LL_K = 54
HpESC_54:
  control_mode: idle
  sign: -1
  pos_offset: 0
  pid :
    position: [500.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 10.0, 5.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 5.0, 0.01, 0.8]

# LL_A_P = 55
HpESC_55:
  control_mode: idle
  sign: -1
  pos_offset: 0
  pid :
    position: [500.0 , 0.0 , 2.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 10.0, 5.0, 0.01, 0.8]

# LL_A_R = 56
HpESC_56:
  control_mode: idle
  sign: -1
  pos_offset: 0
  pid :
    position: [80.0 , 0.0 , 4.0]
    mix_position: [800.0, 0.0, 5.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 10.0, 5.0, 0.01, 0.8]


##############################
# RIGHT ARM
##############################

CentAcESC_11:
  control_mode: idle
  sign: -1
  pos_offset: -45
  max_current_A: 15.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [2000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_12:
  control_mode: idle
  sign: -1
  pos_offset: -45
  max_current_A: 15.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [2000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_13:
  control_mode: idle
  sign: -1
  pos_offset: 0
  max_current_A: 15.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [2000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.2, 0.003, 0.0]

CentAcESC_14:
  control_mode: idle
  sign: -1
  pos_offset: 0
  max_current_A: 15.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.4, 0.003, 0.0]

CentAcESC_15:
  control_mode: idle
  sign: -1
  pos_offset: 0
  max_current_A: 10.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 3.0, 1.0, 0.001, 0.0]

CentAcESC_16:
  control_mode: idle
  sign: -1
  pos_offset: 0
  max_current_A: 10.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 2.0, 1.0, 0.001, 0.0]

CentAcESC_17:
  control_mode: idle
  sign: -1
  pos_offset: 0
  max_current_A: 15.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 3.0, 1.0, 0.001, 0.0]

##############################
# LEFT ARM
##############################
    
CentAcESC_21:
  control_mode: idle
  sign: 1
  pos_offset: -45
  max_current_A: 15.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [2000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_22:
  control_mode: idle
  sign: -1
  pos_offset: 45
  max_current_A: 15.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [2000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_23:
  control_mode: idle
  sign: -1
  pos_offset: 0
  max_current_A: 15.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [2000.0 , 0.0 , 30.0]    
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.2, 0.003, 0.0]
    
CentAcESC_24:
  control_mode: idle
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]    
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.4, 0.003, 0.0]
    
CentAcESC_25:
  control_mode: idle
  sign: -1
  pos_offset: 0
  max_current_A: 10.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 3.0, 1.0, 0.001, 0.0]

CentAcESC_26:
  control_mode: idle
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 2.0, 1.0, 0.001, 0.0]

CentAcESC_27:
  control_mode: idle
  sign: -1
  pos_offset: 0
  max_current_A: 10.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 3.0, 1.0, 0.001, 0.0]

#############################
# WAIST
#############################

CentAcESC_31:
  control_mode: idle
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 2.0, 1.0, 0.001, 0.0]

CentAcESC_32:
  control_mode: idle
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 3.0, 1.0, 0.001, 0.0]



