# WALKMAN 

XBotInterface:
  urdf_path: "configs/ADVR_shared/bigman/urdf/bigman_floating_base.urdf"
  srdf_path: "configs/ADVR_shared/bigman/srdf/bigman.srdf"
  joint_map_path: "configs/ADVR_shared/bigman/joint_map/bigman_ecat_joint_map.yaml"

RobotInterface:
  framework_name: "ROS"

ModelInterface:
  model_type: "RBDL"
  is_model_floating_base: "true"

RobotInterfaceROS:
  subclass_name: "RobotInterfaceROS"
  path_to_shared_lib: "libRobotInterfaceROS.so"
  subclass_factory_name: "robot_interface_ros"
  control_message_type: "AdvrCommandMessage"
  jointstate_message_type: "AdvrJointStateMessage"
  ft_topic_names: ["/xbotcore/bigman/ft/l_arm_ft", "/xbotcore/bigman/ft/l_leg_ft", "/xbotcore/bigman/ft/r_arm_ft", "/xbotcore/bigman/ft/r_leg_ft"]
  imu_topic_names: ["/xbotcore/bigman/imu/imu_link"]

RobotInterfaceXBotRT:
  subclass_name: "RobotInterfaceXBotRT"
  path_to_shared_lib: "libRobotInterfaceXBotRT.so"
  subclass_factory_name: "robot_interface_xbot_rt"

XBotRTPlugins:
  #plugins: ["HomingExample", "IkRosSharedMemoryPublisher", "OpenSotIk", "DebrisRemovalTask", "ManipulationExample"]
  plugins: ["HomingExample", "IkRosSMPub", "OpenSotIk", "Grasp", "chengxu_walking"]
  #io_plugins: ["IkRosIo"]
  io_plugins: ["IkRosIo", "OdomPublisher", "FHRosIo"]
  
NRTPlugins:
  plugins: [ "ManipulationPlugin"]
  ## "DoorOpening", "Hose_Task", "DebrisRemovalTask"

MasterCommunicationInterface:
  framework_name: "ROS"
  
CustomCmnd:
  subclass_name: "CustomCmndMessage"
  path_to_shared_lib: "libCustomCmndMessage.so"
  subclass_factory_name: "customcmnd_control_message"
  joint_service_name: "/bigman/position_controller/get_joint_names"
  command_topic_name: "/bigman/position_controller/command"

JointState:
  subclass_name: "JointStateMessage"
  path_to_shared_lib: "libJointStateMessage.so"
  subclass_factory_name: "jointstate_jointstate_message"
  joint_state_topic_name: "/bigman/joint_states"

AdvrCommandMessage:
  subclass_name: "CommandAdvr"
  path_to_shared_lib: "libAdvrCommandMessage.so"
  subclass_factory_name: "advrcommandmessage_control_message"
  joint_service_name: "/bigman/position_controller/get_joint_names"
  command_topic_name: "/xbotcore/bigman/command"

AdvrJointStateMessage:
  subclass_name: "AdvrJointState"
  path_to_shared_lib: "libAdvrJointStateMessage.so"
  subclass_factory_name: "advrjointstate_jointstate_message"
  joint_state_topic_name: "/xbotcore/bigman/joint_states"

RobotInterfaceDUMMY:
  subclass_name: "RobotInterfaceDUMMY"
  path_to_shared_lib: "libRobotInterfaceDUMMY.so"
  subclass_factory_name: "robot_interface_dummy"

ModelInterfaceRBDL:
  subclass_name: "ModelInterfaceRBDL"
  path_to_shared_lib: "libModelInterfaceRBDL.so"
  subclass_factory_name: "model_interface_rbdl"

GazeboXBotPlugin:
  gains:
    RShSag:   {p: 4000, d: 30}
    RShLat:   {p: 3000, d: 30}
    RShYaw:   {p: 3000, d: 20}
    RElbj:    {p: 3000, d: 20}
    RWrj1:    {p: 1500, d: 10}
    LShSag:   {p: 4000, d: 30}
    LShLat:   {p: 3000, d: 30}
    LShYaw:   {p: 3000, d: 25}
    LElbj:    {p: 3000, d: 25}
    LWrj1:    {p: 1500, d: 10}
    WaistSag: {p: 10000, d: 30}
    WaistYaw: {p: 8000, d: 30}
    WaistLat: {p: 8000, d: 30}
    LHipYaw:  {p: 3000, d: 10}
    RHipYaw:  {p: 3000, d: 10}
    RHipLat:  {p: 15000, d: 80}
    RHipSag:  {p: 15000, d: 80}
    RKneeSag: {p: 15000, d: 80}
    RAnkSag:  {p: 15000, d: 80}
    RAnkLat:  {p: 15000, d: 80}
    LHipLat:  {p: 15000, d: 80}
    LHipSag:  {p: 15000, d: 80}
    LKneeSag: {p: 15000, d: 80}
    LAnkSag:  {p: 15000, d: 80}
    LAnkLat:  {p: 15000, d: 80}

x_bot_ecat:
  name: XBotCore
  sdo_xddp_prefix : 
  # periodic - priority if needed here

ec_board_ctrl:
  eth_iface: rteth0
  sync_cycle_time_ns: 1000000
  sync_cycle_offset_ns: 0
  power_off_boards: true

ec_boards_base:
  create_pipes: true
  
#############################
# HEAD
#############################

#
LpESC_1:
  control_mode: pos_3b
  sign: -1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]
    impedance:  [100.0, 20.0, 2.0, 0.01, 0.8]

#
LpESC_2:
  control_mode: pos_3b
  sign: -1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]
    impedance:  [100.0, 5.0, 2.0, 0.01, 0.8]

#############################
# RIGHT LEG
#############################

# RL_H_R = 41
HpESC_41:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [800.0 , 0.0 , 12.0]
    mix_position: [6000.0, 0.0, 50.0]
    impedance:  [300.0, 65.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]
    

# RL_H_Y = 42
HpESC_42:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [180.0 , 0.0 , 3.0]
    mix_position: [1200.0, 0.0, 20.0]
    impedance:  [300.0, 8.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# RL_H_P = 43
HpESC_43:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [700.0 , 0.0 , 10.0]
    mix_position: [5000.0, 0.0, 45.0]
    impedance:  [300.0, 54.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# RL_K = 44
HpESC_44:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [500.0 , 0.0 , 1.0]
    mix_position: [4500.0, 0.0, 40.0]
    impedance:  [300.0, 30.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# RL_A_P = 45
HpESC_45:
  control_mode: idle
  sign: -1
  pos_offset: 0
  pid :
    position: [500.0 , 0.0 , 2.0]
    mix_position: [4000.0, 0.0, 40.0]
    impedance:  [300.0, 7.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# RL_A_R = 46
HpESC_46:
  control_mode: idle
  sign: -1
  pos_offset: 0
  pid :
    position: [80.0 , 0.0 , 4.0]
    mix_position: [1500.0, 0.0, 20.0]
    impedance:  [300.0, 5.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

#############################
# LEFT LEG
#############################

# LL_H_R = 51
HpESC_51:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [800.0 , 0.0 , 12.0]
    mix_position: [6000.0, 0.0, 50.0]
    impedance:  [300.0, 65.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# LL_H_Y = 52
HpESC_52:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [180.0 , 0.0 , 3.0]
    mix_position: [1200.0, 0.0, 20.0]
    impedance:  [300.0, 8.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# LL_H_P = 53
HpESC_53:
  control_mode: idle
  sign: -1
  pos_offset: 0
  pid :
    position: [700.0 , 0.0 , 10.0]
    mix_position: [5000.0, 0.0, 45.0]
    impedance:  [300.0, 54.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# LL_K = 54
HpESC_54:
  control_mode: idle
  sign: -1
  pos_offset: 0
  pid :
    position: [500.0 , 0.0 , 1.0]
    mix_position: [4500.0, 0.0, 40.0]
    impedance:  [300.0, 30.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# LL_A_P = 55
HpESC_55:
  control_mode: idle
  sign: 1
  pos_offset: 0
  pid :
    position: [500.0 , 0.0 , 2.0]
    mix_position: [4000.0, 0.0, 40.0]
    impedance:  [300.0, 7.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]

# LL_A_R = 56
HpESC_56:
  control_mode: idle
  sign: -1
  pos_offset: 0
  pid :
    position: [80.0 , 0.0 , 4.0]
    mix_position: [1500.0, 0.0, 20.0]
    impedance:  [300.0, 5.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 2.0, 0.01, 0.8]
    #impedance:  [0.0, 0.0, 0.0, 0.0, 0.8]


#############################
# RIGHT ARM
#############################

# RA_SH_1 = 11
HpESC_11:
  control_mode: mix_pos_3c
  sign: 1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]

# RA_SH_2 = 12
HpESC_12:
  control_mode: mix_pos_3c
  sign: 1
  pos_offset: -90
  #pos_offset: -90 NOTE it was not working for the left_arm joint
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]

# RA_SH_3 = 13
HpESC_13:
  control_mode: mix_pos_3c
  sign: 1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]

# RA_EL_ = 14
HpESC_14:
  control_mode: mix_pos_3c
  sign: 1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]

# RA_WR_1 = 15
LpESC_15:
  control_mode: pos_3b
  sign: -1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

# RA_WR_2 = 16
LpESC_16:
  control_mode: pos_3b
  sign: -1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]
    mix_position: [800.0, 0.0, 5.0]

# RA_WR_3 = 17
LpESC_17:
  control_mode: pos_3b
  sign: 1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]
    mix_position: [800.0, 0.0, 5.0]
    impedance:  [100.0, 20.0, 2.0, 0.01, 0.8]

# RA_HA = 19
LpESC_19:
  control_mode: pos_3b
  sign: 1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]
    mix_position: [800.0, 0.0, 5.0]

#############################
# LEFT ARM
#############################

# LA_SH_1 = 21
HpESC_21:
  control_mode: mix_pos_3c
  sign: -1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]

# LA_SH_2 = 22
HpESC_22:
  control_mode: mix_pos_3c
  sign: 1
  pos_offset : 90
  #pos_offset: 90 NOTE it was not working for the left_arm joint
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]

# LA_SH_3 = 23
HpESC_23:
  control_mode: mix_pos_3c
  sign: 1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]

# LA_EL = 24
HpESC_24:
  control_mode: mix_pos_3c
  sign: -1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 5.0]

# LA_WR_1 = 25
LpESC_25:
  control_mode: pos_3b
  sign: -1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

# LA_WR_2 = 26
LpESC_26:
  control_mode: pos_3b
  sign: 1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

# LA_WR_3 = 27
LpESC_27:
  control_mode: pos_3b
  sign: 1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]

# LA_HA = 29
LpESC_29:
  control_mode: pos_3b
  sign: 1
  pos_offset: 0
  pid :
    position: [100000.0 , 0.0 , 0.0]
    mix_position: [800.0, 0.0, 5.0]

#############################
# WAIST
#############################

# WST_Y = 31
HpESC_31:
  control_mode: mix_pos_3c
  sign: -1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 10.0]

# WST_P = 32
HpESC_32:
  control_mode: mix_pos_3c
  sign: 1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [3000.0, 0.0, 30.0]

# WST_R = 33
HpESC_33:
  control_mode: idle
  sign: -1
  pos_offset: 0
  pid :
    position: [40.0 , 0.0 , 1.0]
    mix_position: [800.0, 0.0, 10.0]
