RobotName: "cogimon"

GazeboXBotPlugin:
  control_rate: 0.001
  gains:
    RShSag:        {p: 4000, d: 10}
    RShLat:        {p: 3000, d: 10}
    RShYaw:        {p: 3000, d: 10}
    RElbj:         {p: 3000, d: 10}
    RForearmPlate: {p: 1500, d: 10}
    RWrj1:         {p: 1500, d: 10}
    RWrj2:         {p: 1500, d: 10}
    LShSag:        {p: 4000, d: 10}
    LShLat:        {p: 3000, d: 10}
    LShYaw:        {p: 3000, d: 10}
    LElbj:         {p: 3000, d: 10}
    LForearmPlate: {p: 1500, d: 10}
    LWrj1:         {p: 1500, d: 10}
    LWrj2:         {p: 1500, d: 10}
    WaistYaw:      {p: 8000, d: 30}

HALInterface:
  lib_file: "libXBotEcat"
  lib_name: "ETHERCAT"
  IJoint: "libXBotEcat_Joint"
  
x_bot_ecat:
  name: XBotCore
  sdo_xddp_prefix :
  # periodic - priority if needed here
#
ec_board_ctrl:
  eth_iface: rteth0
  #eth_iface: eth1
  #sync_cycle_time_ns: 500000
  sync_cycle_time_ns: 1000000
  #sync_cycle_time_ns: 2000000
  #sync_cycle_time_ns: 5000000
  #sync_cycle_time_ns: 10000000
  #sync_cycle_time_ns: 0
  sync_cycle_offset_ns: 1000000000
  power_off_boards: false
  use_pipes: false

#
ec_boards_base:
  robot_name : cogimon

#############################
# GENERIC ESC config
#############################

LpESC_X:
  sign: 1
  pos_offset: 0

HpESC_X:
  sign: 1
  pos_offset: 0

CentAcESC_X:
  control_mode: idle
  sign: 1
  pos_offset: 0
  max_current_A: 15.0
  enable_sandbox: false
  enable_pos_filter: false
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [0.0, 0.0, 1.0, 0.002, 0.0]


##############################
# RIGHT ARM
##############################

CentAcESC_11:
  control_mode: idle
  sign: -1
  pos_offset: -45
  max_current_A: 30.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_12:
  control_mode: idle
  sign: -1
  pos_offset: -45
  max_current_A: 30.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_13:
  control_mode: idle
  sign: -1
  pos_offset: 0
  max_current_A: 20.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.2, 0.003, 0.0]

CentAcESC_14:
  control_mode: idle
  sign: -1
  pos_offset: 0
  max_current_A: 20.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.4, 0.003, 0.0]

CentAcESC_15:
  control_mode: idle
  sign: -1
  pos_offset: 0
  max_current_A: 10.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [500.0 , 0.0 , 10.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 3.0, 1.0, 0.001, 0.0]

CentAcESC_16:
  control_mode: idle
  sign: -1
  pos_offset: 0
  max_current_A: 10.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [500.0 , 0.0 , 10.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 2.0, 1.0, 0.001, 0.0]

CentAcESC_17:
  control_mode: idle
  sign: -1
  pos_offset: 0
  max_current_A: 10.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [500.0 , 0.0 , 10.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 3.0, 1.0, 0.001, 0.0] 
    
    

##############################
# LEFT ARM
##############################
    
CentAcESC_21:
  control_mode: idle
  sign: 1
  pos_offset: -45
  max_current_A: 30.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_22:
  control_mode: idle
  sign: -1
  pos_offset: 45
  max_current_A: 30.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.0, 0.003, 0.0]

CentAcESC_23:
  control_mode: idle
  sign: -1
  pos_offset: 0
  max_current_A: 20.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]    
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.2, 0.003, 0.0]
    
CentAcESC_24:
  control_mode: idle
  sign: 1
  pos_offset: 0
  max_current_A: 20.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]    
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 0.0, 1.4, 0.003, 0.0]
    
CentAcESC_25:
  control_mode: idle
  sign: -1
  pos_offset: 0
  max_current_A: 10.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [500.0 , 0.0 , 10.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 3.0, 1.0, 0.001, 0.0]

CentAcESC_26:
  control_mode: idle
  sign: 1
  pos_offset: 0
  max_current_A: 10.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [500.0 , 0.0 , 10.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 2.0, 1.0, 0.001, 0.0]

CentAcESC_27:
  control_mode: idle
  sign: -1
  pos_offset: 0
  max_current_A: 10.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [500.0 , 0.0 , 10.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [100.0, 3.0, 1.0, 0.001, 0.0] 

#############################
# WAIST
#############################

CentAcESC_31:
  control_mode: idle
  sign: 1
  pos_offset: 0
  max_current_A: 30.0
  enable_sandbox: false
  enable_pos_filter: true
  pid :
    position: [1000.0 , 0.0 , 30.0]
    #  .... tor_K divided by 10000 to respect the int range [0..65536]
    impedance:  [50.0, 2.0, 1.0, 0.001, 0.0]



